export default [
    {id: 0, name: 'Metro Fuel Marrickville'},
    {id: 1, name: 'Speedway Smithfield'},
    {id: 2, name: 'Speedway Fairfield'},
    {id: 3, name: 'Speedway Westmead'},
    {id: 4, name: 'Speedway Horsley Drive'},
    {id: 5, name: 'BP North Rocks'},
    {id: 6, name: 'BP CLOVELLY'},
    {id: 7, name: 'Metro Lansdowne'},
    {id: 8, name: 'Metro Fuel Ermington'},
    {id: 9, name: 'Metro Fuel Greystanes'},
    {id: 10, name: 'Metro Fuel Old Toongabbie'},
    {id: 11, name: 'BP Chipping Norton'},
    {id: 12, name: 'Budget Oatley'},
    {id: 13, name: 'Enhance Homebush'},
    {id: 14, name: 'Speedway Kent Road'},
    {id: 15, name: 'Budget North Rocks'},
    {id: 16, name: 'Budget Kogarah'},
    {id: 17, name: 'Speedway Liverpool'},
    {id: 18, name: 'Caltex Villawood'},
    {id: 19, name: 'Budget Annangrove'},
    {id: 20, name: 'Budget Carlton'},
    {id: 21, name: 'Caltex Woolworths Prestons'},
    {id: 22, name: 'Caltex Woolworths Kogarah'},
    {id: 23, name: 'BP Willoughby'},
    {id: 24, name: 'Independent Lalor Park'},
    {id: 25, name: 'Metro Georges Hall'},
    {id: 26, name: 'Caltex Woolworths Seven Hills North'},
    {id: 27, name: 'Caltex Woolworths Chester Hill'},
    {id: 28, name: 'Metro Auburn'},
    {id: 29, name: 'Caltex starmart Newtown'},
    {id: 30, name: 'Caltex Star Mart Coogee South'},
    {id: 31, name: 'Caltex Kemps Creek'},
    {id: 32, name: 'Caltex Coogee'},
    {id: 33, name: 'Caltex Woolworths Rosebery'},
    {id: 34, name: 'Caltex Star Mart Tempe'},
    {id: 35, name: 'Caltex Greenacre'},
    {id: 36, name: '7-Eleven Sans Souci'},
    {id: 37, name: '7-Eleven South Hurstville'},
    {id: 38, name: '7-Eleven Toongabbie'},
    {id: 39, name: 'Caltex Ermington'},
    {id: 40, name: 'Caltex old Guildford'},
    {id: 41, name: 'Caltex Star Mart Bonnyrigg'},
    {id: 42, name: '7-Eleven Guildford'},
    {id: 43, name: 'Speedway Kings Langley'},
    {id: 44, name: 'Westside Petroleum Lidcombe'},
    {id: 45, name: 'Metro Petroleum Padstow'},
    {id: 46, name: 'Caltex Woolworths West Ryde'},
    {id: 47, name: 'Budget Brighton'},
    {id: 48, name: 'Caltex Starmart Lakemba'},
    {id: 49, name: 'Metro Petroleum Belmore'},
    {id: 50, name: 'Metro Fuel Canterbury'},
    {id: 51, name: '7-Eleven Carlton'},
    {id: 52, name: '7-Eleven Seven Hills'},
    {id: 53, name: '7-Eleven Baulkham Hills'},
    {id: 54, name: '7-Eleven Kogarah'},
    {id: 55, name: '7-Eleven Guildford West'},
    {id: 56, name: 'Caltex Woolworths Chipping Norton'},
    {id: 57, name: '7-Eleven Mount Pritchard'},
    {id: 58, name: 'Speedway Rockdale'},
    {id: 59, name: 'Metro Fuel Fairfield'},
    {id: 60, name: 'Caltex Woolworths Bonnyrigg'},
    {id: 61, name: 'Caltex Woolworths Seven Hills'},
    {id: 62, name: 'BP CONCORD'},
    {id: 63, name: 'Independent Liverpool'},
    {id: 64, name: 'Caltex Woolworths Blakehurst'},
    {id: 65, name: 'BP Bondi'},
    {id: 66, name: 'Caltex Woolworths Rockdale'},
    {id: 67, name: 'United Bass Hill'},
    {id: 68, name: 'Speedway South Granville'},
    {id: 69, name: 'BP Redfern'},
    {id: 70, name: 'SPEEDWAY FAIRFIELD WEST'},
    {id: 71, name: 'Speedway Auburn'},
    {id: 72, name: 'BP Cabramatta West'},
    {id: 73, name: 'APEX PETROLEUM (WEST RYDE)'},
    {id: 74, name: 'BP Greystanes'},
    {id: 75, name: 'Budget Blacktown'},
    {id: 76, name: 'Speedway Granville'},
    {id: 77, name: 'BP Blacktown'},
    {id: 78, name: 'APEX PETROLEUM VILLAWOOD'},
    {id: 79, name: 'Budget Granville'},
    {id: 80, name: 'Metro Fuel Regents Park'},
    {id: 81, name: 'BP Sans Souci'},
    {id: 82, name: 'Metro St Ives Chase'},
    {id: 83, name: 'Caltex Woolworths Surry Hills'},
    {id: 84, name: 'Independent Roselands'},
    {id: 85, name: '7-Eleven Rockdale'},
    {id: 86, name: ''},
    {id: 87, name: '7-Eleven Prairewood'},
    {id: 88, name: '7-Eleven Blacktown East'},
    {id: 89, name: '7-Eleven Arncliffe'},
    {id: 90, name: '7-Eleven Kirrawee'},
    {id: 91, name: 'Budget Petroleum Smithfield'},
    {id: 92, name: 'BP Sydenham'},
    {id: 93, name: '7-Eleven West Ryde'},
    {id: 94, name: 'BP Regent Street'},
    {id: 95, name: 'Budget Kingsgrove'},
    {id: 96, name: 'BP Bonnyrigg'},
    {id: 97, name: 'BP Silverwater'},
    {id: 98, name: 'BP Crossroads'},
    {id: 99, name: 'BP Rose Bay Central'},
    {id: 100, name: 'Speedway Woodpark'},
    {id: 101, name: 'BP Seven Hills'},
    {id: 102, name: 'Metro Punchbowl'},
    {id: 103, name: 'BP West Ryde'},
    {id: 104, name: 'Budget Dulwich Hill'},
    {id: 105, name: 'Caltex Woolworths Roselands'},
    {id: 106, name: 'Caltex Woolworths Granville'},
    {id: 107, name: 'Caltex Woolworths Marrickville'},
    {id: 108, name: 'Caltex Seven Hills'},
    {id: 109, name: 'Caltex Star Mart Bondi'},
    {id: 110, name: 'Caltex Kogarah'},
    {id: 111, name: 'Budget Freshwater'},
    {id: 112, name: 'BP Lansvale'},
    {id: 113, name: 'Caltex Mount Pritchard'},
    {id: 114, name: 'Caltex Merrylands'},
    {id: 115, name: 'Powerfuel'},
    {id: 116, name: 'BP Berowra'},
    {id: 117, name: 'Caltex Leppington'},
    {id: 118, name: 'Caltex Woolworths Blacktown'},
    {id: 119, name: '7-Eleven Paddington'},
    {id: 120, name: 'Caltex Starmart Casula'},
    {id: 121, name: 'Caltex Star Mart Seven Hills'},
    {id: 122, name: 'Ampol Hoxton Park'},
    {id: 123, name: 'Westside Petroleum Granville'},
    {id: 124, name: 'Caltex Woolworths Lansvale'},
    {id: 125, name: 'Speedway Green Valley'},
    {id: 126, name: 'Budget Petrol Bundeena'},
    {id: 127, name: '7-Eleven Ryde'},
    {id: 128, name: '7-Eleven Belmore'},
    {id: 129, name: 'BP Silverwater South'},
    {id: 130, name: 'BP Mays Hill'},
    {id: 131, name: 'BP Kemps Creek'},
    {id: 132, name: 'Tanwar Petroleum'},
    {id: 133, name: 'Speedway Blacktown'},
    {id: 134, name: 'Metro Fuel Miranda'},
    {id: 135, name: 'BP Padstow'},
    {id: 136, name: 'Fairfield Fuel'},
    {id: 137, name: 'Caltex Woolworths Merrylands'},
    {id: 138, name: 'Caltex Woolworths Silverwater'},
    {id: 139, name: 'Caltex Woolworths Newington'},
    {id: 140, name: 'Coles Express Bass Hill'},
    {id: 141, name: 'Speedway Villawood'},
    {id: 142, name: '7-Eleven Lansvale South'},
    {id: 143, name: 'Budget Chester Hill'},
    {id: 144, name: 'Coles Express Edmondson Park'},
    {id: 145, name: 'Liberty Bonnyrigg'},
    {id: 146, name: 'Metro Yagoona'},
    {id: 147, name: 'Coles Express Yagoona'},
    {id: 148, name: '7-Eleven Georges Hall'},
    {id: 149, name: 'BP Riverwood'},
    {id: 150, name: 'BP Fairfield'},
    {id: 151, name: 'BP Putney'},
    {id: 152, name: 'CALTEX IGA EXPRESS'},
    {id: 153, name: '7-Eleven Lakemba'},
    {id: 154, name: 'Speedway Croydon'},
    {id: 155, name: 'Speedway Cammeray'},
    {id: 156, name: '7-Eleven Yagoona'},
    {id: 157, name: '7-Eleven Bankstown'},
    {id: 158, name: 'Speedway Austral'},
    {id: 159, name: 'Budget Petrol Chippendale'},
    {id: 160, name: '7-Eleven Emerald Hills'},
    {id: 161, name: 'Metro Wakely'},
    {id: 162, name: 'Metro Revesby'},
    {id: 163, name: 'Caltex Ryde Self Serve'},
    {id: 164, name: 'Caltex Woolworths Burwood'},
    {id: 165, name: 'United Petroleum Kemps Creek'},
    {id: 166, name: 'Metro Fuel Homebush'},
    {id: 167, name: 'Metro Petroleum Liverpool'},
    {id: 168, name: 'Metro Pertoleum Lurnea'},
    {id: 169, name: 'Metro Condell Park West'},
    {id: 170, name: 'Caltex Woolworths Marsfield'},
    {id: 171, name: 'Caltex Woolworths Chatswood East'},
    {id: 172, name: 'BP South Hurstville'},
    {id: 173, name: 'Budget Petrol'},
    {id: 174, name: 'Independent Lakemba'},
    {id: 175, name: 'Metro Randwick'},
    {id: 176, name: 'BP Randwick'},
    {id: 177, name: 'Caltex Woolworths Bass Hill'},
    {id: 178, name: 'BP Condell Park'},
    {id: 179, name: 'Coles Express Taren Point'},
    {id: 180, name: 'Coles Express Brighton-Le-Sands'},
    {id: 181, name: 'Coles Express Drummoyne'},
    {id: 182, name: 'Coles Express Lidcombe'},
    {id: 183, name: 'Coles Express Maroubra'},
    {id: 184, name: 'Coles Express North Ryde'},
    {id: 185, name: 'Coles Express Lane Cove'},
    {id: 186, name: 'Coles Express Randwick'},
    {id: 187, name: 'Coles Express Leppington'},
    {id: 188, name: 'Coles Express Green Valley'},
    {id: 189, name: 'Coles Express Forestville'},
    {id: 190, name: 'Coles Express Bondi Junction'},
    {id: 191, name: 'Coles Express Guildford'},
    {id: 192, name: 'Coles Express Wetherill Park'},
    {id: 193, name: 'Coles Express Carlingford'},
    {id: 194, name: 'Coles Express Wattle Grove'},
    {id: 195, name: 'Coles Express Canley Vale'},
    {id: 196, name: 'Coles Express Five Dock'},
    {id: 197, name: 'Coles Express Marsfield'},
    {id: 198, name: 'Coles Express Greystanes'},
    {id: 199, name: 'Coles Express Padstow'},
    {id: 200, name: 'Coles Express Ryde'},
    {id: 201, name: 'Coles Express Oyster Bay'},
    {id: 202, name: 'Coles Express South Hurstville'},
    {id: 203, name: 'Coles Express Willoughby'},
    {id: 204, name: 'Coles Express Baulkham Hills'},
    {id: 205, name: 'Coles Express Smithfield'},
    {id: 206, name: 'Coles Express Northmead'},
    {id: 207, name: 'Coles Express Pagewood'},
    {id: 208, name: 'Coles Express Blacktown'},
    {id: 209, name: 'Coles Express Gymea'},
    {id: 210, name: 'Coles Express Kingsford'},
    {id: 211, name: 'Coles Express West Ryde'},
    {id: 212, name: 'Coles Express Alexandria'},
    {id: 213, name: 'Coles Express Chatswood'},
    {id: 214, name: 'Coles Express Bexley'},
    {id: 215, name: 'Coles Express Fairfield'},
    {id: 216, name: 'Coles Express Ramsgate'},
    {id: 217, name: '7-Eleven North Ryde'},
    {id: 218, name: '7-Eleven Revesby South'},
    {id: 219, name: '7-Eleven Epping'},
    {id: 220, name: '7-Eleven Fairfield West'},
    {id: 221, name: 'Coles Express Carlton'},
    {id: 222, name: 'Caltex Woolworths Moorebank'},
    {id: 223, name: '7-Eleven Revesby'},
    {id: 224, name: 'Coles Express Waterloo'},
    {id: 225, name: 'BP North Manly'},
    {id: 226, name: 'Caltex Woolworths Woolooware'},
    {id: 227, name: 'Caltex Woolworths Marayong'},
    {id: 228, name: 'Caltex Woolworths Glenrose'},
    {id: 229, name: 'Caltex Woolworths Randwick'},
    {id: 230, name: 'Caltex Cabramatta'},
    {id: 231, name: 'Caltex Starmart Lansvale'},
    {id: 232, name: 'Caltex Beacon Hill'},
    {id: 233, name: 'Caltex Gladesville'},
    {id: 234, name: 'Caltex Star Mart Wetherill Park'},
    {id: 235, name: 'Caltex Star Mart Chatswood'},
    {id: 236, name: 'CALTEX MOOREBANK'},
    {id: 237, name: 'Caltex Wentworthville'},
    {id: 238, name: 'Caltex Woolworths Miranda'},
    {id: 239, name: 'BP Horsley Park'},
    {id: 240, name: 'Caltex Kirrawee'},
    {id: 241, name: '7-Eleven Blacktown'},
    {id: 242, name: 'Metro Fuel Killarney Heights'},
    {id: 243, name: 'Metro Petroleum Forestville'},
    {id: 244, name: 'Metro Pendle Hill'},
    {id: 245, name: '7-Eleven Carlingford'},
    {id: 246, name: 'Caltex Star Mart Drummoyne'},
    {id: 247, name: 'Caltex Chipping Norton'},
    {id: 248, name: 'Caltex Starmart Homebush'},
    {id: 249, name: 'Caltex Taren Point'},
    {id: 250, name: 'Caltex Star Mart Canley Heights'},
    {id: 251, name: 'Caltex Padstow'},
    {id: 252, name: 'Caltex North Ryde'},
    {id: 253, name: 'Caltex Sylvania Heights'},
    {id: 254, name: 'Caltex Pendle Hill'},
    {id: 255, name: 'Caltex Woolworths Fairfield Heights'},
    {id: 256, name: '7-Eleven Matraville'},
    {id: 257, name: '7-Eleven Edmondson Park'},
    {id: 258, name: '7-Eleven Five Dock'},
    {id: 259, name: '7-Eleven Sutherland'},
    {id: 260, name: '7-Eleven Drummoyne'},
    {id: 261, name: '7-Eleven Maroubra'},
    {id: 262, name: '7-Eleven Caringbah'},
    {id: 263, name: '7-Eleven Gymea'},
    {id: 264, name: '7-Eleven Arndell Park'},
    {id: 265, name: '7-Eleven Lane Cove'},
    {id: 266, name: '7-Eleven Artarmon'},
    {id: 267, name: '7-Eleven Fairfield'},
    {id: 268, name: 'Speedway Bass Hill'},
    {id: 269, name: '7-Eleven Kensington'},
    {id: 270, name: '7-Eleven Casula'},
    {id: 271, name: '7-Eleven Rozelle'},
    {id: 272, name: '7-Eleven Castle Hill'},
    {id: 273, name: '7-Eleven Roseville'},
    {id: 274, name: '7-Eleven Moorebank'},
    {id: 275, name: '7-Eleven Northmead'},
    {id: 276, name: '7-Eleven Bexley'},
    {id: 277, name: 'Caltex Woolworths Brookvale'},
    {id: 278, name: 'BP Yagoona'},
    {id: 279, name: 'Budget Moorebank'},
    {id: 280, name: 'Coles Express Kingsgrove'},
    {id: 281, name: 'Coles Express Pennant Hills'},
    {id: 282, name: 'Coles Express Hunters Hill'},
    {id: 283, name: 'Caltex Woolworths Prospect'},
    {id: 284, name: 'SHELL LANSVALE WEST'},
    {id: 285, name: 'Caltex Starmart Brookvale'},
    {id: 286, name: 'Caltex Wow Rozelle'},
    {id: 287, name: 'Caltex Lane Cove West'},
    {id: 288, name: 'Caltex Belrose'},
    {id: 289, name: 'CALTEX STAR SHOP CARLINGFORD COURT'},
    {id: 290, name: 'Caltex Crows Nest'},
    {id: 291, name: 'Caltex Kensington'},
    {id: 292, name: 'Caltex Longueville'},
    {id: 293, name: 'Caltex Northmead'},
    {id: 294, name: 'Caltex Woolworths Carlingford'},
    {id: 295, name: 'Caltex Kingsford'},
    {id: 296, name: 'United Petroleum Yagoona'},
    {id: 297, name: 'BP West Pennant Hills'},
    {id: 298, name: '7-Eleven Edensor Park'},
    {id: 299, name: 'United Petroleum Dee Why'},
    {id: 300, name: 'Coles Express Stanmore'},
    {id: 301, name: 'Budget Bexley'},
    {id: 302, name: 'BP Express Northwood'},
    {id: 303, name: 'Coles Express Woolloomooloo'},
    {id: 304, name: 'Coles Express Berowra'},
    {id: 305, name: 'Coles Express Hoxton Park'},
    {id: 306, name: 'Coles Express Cabramatta'},
    {id: 307, name: 'Coles Express Casula'},
    {id: 308, name: 'Coles Express Hurstville'},
    {id: 309, name: 'Coles Express Cremorne'},
    {id: 310, name: 'Coles Express Parramatta'},
    {id: 311, name: 'Caltex Woolworths Carnes Hill'},
    {id: 312, name: 'Budget Campsie'},
    {id: 313, name: 'Coles Express Hornsby'},
    {id: 314, name: 'Coles Express Narrabeen'},
    {id: 315, name: 'Coles Express Greenacre'},
    {id: 316, name: 'Coles Express Liverpool'},
    {id: 317, name: 'Coles Express Strathfield'},
    {id: 318, name: 'Coles Express Annandale'},
    {id: 319, name: 'Coles Express Rouse Hill'},
    {id: 320, name: 'Coles Express Heathcote'},
    {id: 321, name: 'Coles Express Brookvale'},
    {id: 322, name: 'Coles Express Dundas'},
    {id: 323, name: 'Coles Express Thornleigh'},
    {id: 324, name: 'Coles Express Ultimo'},
    {id: 325, name: '7-Eleven Pendle Hill'},
    {id: 326, name: '7-Eleven Kings Park'},
    {id: 327, name: '7-Eleven Woolooware'},
    {id: 328, name: '7-Eleven Kellyville'},
    {id: 329, name: '7-Eleven North Rocks'},
    {id: 330, name: 'Coles Express Avalon Beach'},
    {id: 331, name: '7-Eleven Dee Why'},
    {id: 332, name: '7-Eleven Strathfield South'},
    {id: 333, name: '7-Eleven Merrylands'},
    {id: 334, name: '7-Eleven West Pennant Hills'},
    {id: 335, name: '7-Eleven Greenacre'},
    {id: 336, name: 'Coles Express Neutral Bay'},
    {id: 337, name: 'Coles Express Dural'},
    {id: 338, name: 'Coles Express Wahroonga'},
    {id: 339, name: 'Coles Express Cammeray'},
    {id: 340, name: 'BP Carss Park'},
    {id: 341, name: 'Independent Glenfield'},
    {id: 342, name: '7-Eleven Parramatta'},
    {id: 343, name: 'Coles Express Pymble'},
    {id: 344, name: 'Coles Express St Ives'},
    {id: 345, name: 'Coles Express Strathfield South'},
    {id: 346, name: 'Metro Petroleum Blacktown'},
    {id: 347, name: 'West Yagoona BP'},
    {id: 348, name: 'METRO SUNNYHOLT RD BLACKTOWN'},
    {id: 349, name: 'Caltex Woolworths Kellyville'},
    {id: 350, name: 'Caltex Woolworths Strathfield'},
    {id: 351, name: 'Caltex Woolworths Chullora'},
    {id: 352, name: '7-Eleven Mosman'},
    {id: 353, name: '7-Eleven Berowra'},
    {id: 354, name: 'Payless Fuel Sydenham'},
    {id: 355, name: 'BP Allambie Heights'},
    {id: 356, name: 'United Petroleum Waterloo'},
    {id: 357, name: 'Speedway Miranda'},
    {id: 358, name: 'BP Enfield'},
    {id: 359, name: 'BP Mascot'},
    {id: 360, name: 'Metro Fuel Blacktown'},
    {id: 361, name: 'Metro Belmore'},
    {id: 362, name: 'United Petroleum Yagoona South'},
    {id: 363, name: 'BP Gymea'},
    {id: 364, name: 'Westside Freshwater'},
    {id: 365, name: 'Ultra Manly'},
    {id: 366, name: 'Metro Toongabbie'},
    {id: 367, name: 'Caltex Woolworths Bankstown'},
    {id: 368, name: 'Caltex Woolworths Menai'},
    {id: 369, name: 'Metro Petroleum Bexley North'},
    {id: 370, name: 'Caltex Woolworths Turramurra'},
    {id: 371, name: 'Metro Fuel Kogarah'},
    {id: 372, name: 'Budget Auburn'},
    {id: 373, name: 'Metro Fairfield'},
    {id: 374, name: 'Metro Fuel Condell Park'},
    {id: 375, name: 'BP Kirrawee'},
    {id: 376, name: 'BP Bexley'},
    {id: 377, name: 'Metro Bankstown'},
    {id: 378, name: 'Speedway West Ryde'},
    {id: 379, name: 'BUDGET PETROL ASHFIELD'},
    {id: 380, name: 'Metro Leichhardt'},
    {id: 381, name: 'Caltex North Bondi'},
    {id: 382, name: 'Caltex Rosebay'},
    {id: 383, name: 'Caltex Woolworths Woollahra'},
    {id: 384, name: 'Caltex Moorebank'},
    {id: 385, name: 'Caltex Star Mart Dee Why'},
    {id: 386, name: 'Caltex Alexandria'},
    {id: 387, name: 'Caltex Starmart Punchbowl'},
    {id: 388, name: 'Caltex Mascot'},
    {id: 389, name: 'Caltex Manly Vale'},
    {id: 390, name: 'Caltex Strathfield South'},
    {id: 391, name: 'The Foodary Croydon'},
    {id: 392, name: 'Costco Casula (Members only)'},
    {id: 393, name: 'Caltex Menai'},
    {id: 394, name: 'Caltex Kellyville'},
    {id: 395, name: 'Caltex Star Mart Cherrybrook'},
    {id: 396, name: 'Caltex Lilli Pilli'},
    {id: 397, name: 'Caltex Woolooware'},
    {id: 398, name: 'Caltex Woolworths Greenacre'},
    {id: 399, name: 'AP Punchbowl'},
    {id: 400, name: 'Coles Express Merrylands'},
    {id: 401, name: 'Speedway Arncliffe'},
    {id: 402, name: 'shell cromer'},
    {id: 403, name: 'BP Warwick Farm'},
    {id: 404, name: 'Budget Petrol Matraville'},
    {id: 405, name: 'Caltex Woolworths North Narrabeen'},
    {id: 406, name: 'Caltex Woolworths Newport'},
    {id: 407, name: 'Caltex Woolworths Peakhurst'},
    {id: 408, name: 'BP Loftus'},
    {id: 409, name: '7-Eleven Liverpool'},
    {id: 410, name: '7-Eleven Narrabeen'},
    {id: 411, name: '7-Eleven Menai'},
    {id: 412, name: '7-Eleven Croydon Park'},
    {id: 413, name: '7-Eleven Riverwood'},
    {id: 414, name: '7-Eleven Ashfield'},
    {id: 415, name: '7-Eleven Penshurst'},
    {id: 416, name: '7-Eleven Newport'},
    {id: 417, name: '7-Eleven Mona Vale'},
    {id: 418, name: 'BP FOX HILLS'},
    {id: 419, name: 'Caltex Woolworths North Liverpool'},
    {id: 420, name: 'BP Roseville'},
    {id: 421, name: 'BP Denistone East'},
    {id: 422, name: 'Independent West Pymble'},
    {id: 423, name: 'United Petroleum Dee Why Pittwater'},
    {id: 424, name: 'Caltex Narwee'},
    {id: 425, name: 'Caltex Star Mart Penshurst'},
    {id: 426, name: 'Caltex Woolworths'},
    {id: 427, name: 'Caltex Kingsgrove'},
    {id: 428, name: 'Caltex Woolworths Revesby'},
    {id: 429, name: 'Independent Canley Heights'},
    {id: 430, name: 'Budget Petrol Eastlakes'},
    {id: 431, name: 'BP Artarmon'},
    {id: 432, name: 'BP Forestville'},
    {id: 433, name: 'Speedway Bankstown'},
    {id: 434, name: 'BP Balgowlah'},
    {id: 435, name: 'BP Naremburn'},
    {id: 436, name: 'BP Carlingford'},
    {id: 437, name: 'Caltex Neutral Bay'},
    {id: 438, name: 'United Prairiewood'},
    {id: 439, name: 'BP Thornleigh'},
    {id: 440, name: 'Caltex Star Mart Concord West'},
    {id: 441, name: 'BP Summer Hill'},
    {id: 442, name: 'BP Pymble'},
    {id: 443, name: 'METRO PETROLEUM HURLSTONE PARK'},
    {id: 444, name: 'BP Cronulla'},
    {id: 445, name: 'BP Canterbury'},
    {id: 446, name: 'BP Potts Hill T/S'},
    {id: 447, name: 'BP Milperra'},
    {id: 448, name: 'Caltex Star Mart Narrabeen'},
    {id: 449, name: 'BP Revesby'},
    {id: 450, name: 'Shell Liverpool'},
    {id: 451, name: 'BP Ashfield'},
    {id: 452, name: 'BP Bankstown Airport'},
    {id: 453, name: 'BP Wiley Park'},
    {id: 454, name: 'BP Rozelle'},
    {id: 455, name: 'BP Kingsford'},
    {id: 456, name: 'BP Mortdale'},
    {id: 457, name: 'BP South Moorebank'},
    {id: 458, name: 'Independent Girraween'},
    {id: 459, name: 'Caltex Hornsby Heights'},
    {id: 460, name: 'BP Casula'},
    {id: 461, name: '7-Eleven Haberfield'},
    {id: 462, name: '7-Eleven Bonnyrigg'},
    {id: 463, name: '7-Eleven Petersham'},
    {id: 464, name: '7-Eleven St Ives'},
    {id: 465, name: '7-Eleven Wahroonga'},
    {id: 466, name: '7-Eleven Hurlstone Park'},
    {id: 467, name: '7-Eleven Lindfield'},
    {id: 468, name: '7-Eleven Turramurra'},
    {id: 469, name: '7-Eleven Killara'},
    {id: 470, name: 'Metro Castle Cove'},
    {id: 471, name: 'Caltex Woolworths Leichardt'},
    {id: 472, name: 'BP Dundas'},
    {id: 473, name: 'Caltex St Ives'},
    {id: 474, name: 'BP Kingsgrove'},
    {id: 475, name: '7-Eleven Camperdown'},
    {id: 476, name: 'Caltex St Ives North'},
    {id: 477, name: 'BOBBIN HEAD PETROL STATION'},
    {id: 478, name: 'Independent West Hoxton'},
    {id: 479, name: 'BP Guildford'},
    {id: 480, name: 'Metro Fuel'},
    {id: 481, name: 'Metro Petroleum Earlwood'},
    {id: 482, name: 'METRO CROYDON PARK'},
    {id: 483, name: 'Metro Fuel Jannali'},
    {id: 484, name: 'Metro Tempe'},
    {id: 485, name: 'Enhance Granville'},
    {id: 486, name: 'BP Matraville'},
    {id: 487, name: 'Metro Fuel North Avalon'},
    {id: 488, name: 'Metro Fuel Greenacre'},
    {id: 489, name: 'Metro revesby west'},
    {id: 490, name: 'BP Lugarno'},
    {id: 491, name: 'Metro Petroleum Narwee'},
    {id: 492, name: 'BP Turramurra'},
    {id: 493, name: 'Metro Marrickville'},
    {id: 494, name: 'Westside Greenacre'},
    {id: 495, name: 'BP Botany'},
    {id: 496, name: 'Metro Bonnyrigg'},
    {id: 497, name: 'Metro Peakhurst'},
    {id: 498, name: 'Metro Petroleum South Hurstville'},
    {id: 499, name: 'Metro Lane Cove'},
    {id: 500, name: 'United Terrey HILLS'},
    {id: 501, name: 'Caltex Woolworths Dural'},
    {id: 502, name: '7-Eleven Enmore'},
    {id: 503, name: 'Caltex Woolworths Hoxton Park'},
    {id: 504, name: '7-Eleven Green Valley'},
    {id: 505, name: 'Caltex Heathcote'},
    {id: 506, name: 'Caltex Woolworths Waitara'},
    {id: 507, name: 'Caltex WOW Heathcote'},
    {id: 508, name: 'Caltex Star Mart Dural'},
    {id: 509, name: 'Caltex Berowra'},
    {id: 510, name: '7-Eleven Burwood'},
    {id: 511, name: '7-Eleven Lurnea'},
    {id: 512, name: 'Caltex Mount Colah'},
    {id: 513, name: 'Caltex Kenthurst'},
    {id: 514, name: 'Metro Peakhurst East'},
    {id: 515, name: 'Westside Kenthurst'},
    {id: 516, name: 'BP Kellyville'},
    {id: 517, name: 'BP St Peters (NSW)'},
    {id: 518, name: 'BP Rosehill'},
    {id: 519, name: 'BP Runway'},
    {id: 520, name: 'BP Asquith'},
    {id: 521, name: 'Caltex Starmart Concord'},
    {id: 522, name: 'Metro Petroleum Chester Hill'},
    {id: 523, name: 'Speedway Revesby'},
    {id: 524, name: 'BP Hoxton Park'},
    {id: 525, name: 'Metro Fuel Alexandria'},
    {id: 526, name: '7 Express Carlton'},
    {id: 527, name: 'BP Bankstown'},
    {id: 528, name: 'Caltex Star Mart Rydalmere'},
    {id: 529, name: 'Caltex Woolworths Baulkham Hills 22464'},
    {id: 530, name: 'Metro Petroleum Lakemba'},
    {id: 531, name: 'BP Manly'},
    {id: 532, name: 'Caltex Miller'},
    {id: 533, name: 'Metro Fuel Wiley Park'},
    {id: 534, name: 'BP Bexley North'},
    {id: 535, name: '7-Eleven Granville'},
    {id: 536, name: '7-Eleven Granville East'},
    {id: 537, name: 'United Petroleum Rydalmere'},
    {id: 538, name: 'BUDGET PETROL BEXLEY ROAD CAMPSIE'},
    {id: 539, name: 'Caltex Granville'},
    {id: 540, name: 'Caltex Starmart Manly'},
    {id: 541, name: 'BP Auburn'},
    {id: 542, name: 'Budget Petrol Petersham'},
    {id: 543, name: 'BP Leppington'},
    {id: 544, name: 'Independent Marrickville'},
    {id: 545, name: 'BP Thornton'},
    {id: 546, name: 'Speedway Mt Pritchard'},
    {id: 547, name: 'Speedway Meadows'},
    {id: 548, name: 'Metro Milperra'},
    {id: 549, name: 'BP Greenfield Park'},
    {id: 550, name: 'BP Merrylands West'},
    {id: 551, name: 'BP Hoxton Park Airfield'},
    {id: 552, name: 'United Sutherland'},
    {id: 553, name: 'BP Mosman (0926)'},
    {id: 554, name: 'BP Mona Vale'},
    {id: 555, name: 'BP Hornsby'},
    {id: 556, name: 'BP Dural'},
    {id: 557, name: 'BP Caringbah'},
    {id: 558, name: 'BP Peninsula'},
    {id: 559, name: 'BP Engadine'},
    {id: 560, name: 'Metro Fuel Hornsby'},
    {id: 561, name: 'BP Rydalmere'},
    {id: 562, name: 'BP Camperdown'},
    {id: 563, name: 'Independent Ramsgate'},
    {id: 564, name: 'BP Prestons'},
    {id: 565, name: 'Budget Erskineville'},
    {id: 566, name: 'BP Liverpool'},
    {id: 567, name: 'BP Rockdale'},
    {id: 568, name: 'BP Croydon Park'},
    {id: 569, name: 'BP Normanhurst'},
    {id: 570, name: 'Independent Turramurra'},
    {id: 571, name: 'BP Baulkham Hills'},
    {id: 572, name: 'BP Rose Bay'},
    {id: 573, name: 'Calvi Petrol Station'},
    {id: 574, name: 'Metro Bexley'},
    {id: 575, name: 'Metro Willoughby'},
    {id: 576, name: 'Metro Sefton'},
    {id: 577, name: 'BP Haberfield'},
    {id: 578, name: 'BP Belfield'},
    {id: 579, name: 'Independent Rosebery'},
    {id: 580, name: 'Independent Wiley Park'},
    {id: 581, name: 'Metro Fuel Cremorne'},
    {id: 582, name: 'Enhance Merrylands'},
    {id: 583, name: 'Speedway Regents Park'},
    {id: 584, name: 'Speedway Parramatta'},
    {id: 585, name: 'BUDGET PETROL MASCOT'},
    {id: 586, name: 'Caltex Horsley Park'},
    {id: 587, name: 'United Beacon Hill'},
    {id: 588, name: 'Xpress fuels'},
    {id: 589, name: 'BP Epping'},
    {id: 590, name: 'United Rozelle'},
    {id: 591, name: 'Budget Earlwood'},
    {id: 592, name: 'Metro Fuel Haberfield'},
    {id: 593, name: 'Westside Blakehurst'},
    {id: 594, name: 'BP Penshurst'},
    {id: 595, name: 'Sparkles Petroleum Clovelly'},
    {id: 596, name: 'Speedway Haberfield'},
    {id: 597, name: 'BP Smithfield'},
    {id: 598, name: 'Speedway Caringbah'},
    {id: 599, name: 'BP Lane Cove'},
    {id: 600, name: 'Speedway Birrong'},
    {id: 601, name: 'Budget Telopea'},
    {id: 602, name: 'Budget West Ryde'},
    {id: 603, name: 'Prime Earlwood'},
    {id: 604, name: 'Speedway Casula'},
    {id: 605, name: 'Speedway Northwood'},
    {id: 606, name: 'APW'},
    {id: 607, name: 'BP Edgecliff'},
    {id: 608, name: 'Gas to connect'},
    {id: 609, name: 'Metro Fuel Croydon'},
    {id: 610, name: 'Mobil 1 Carlingford Car Care'},
    {id: 611, name: 'Puma Wetherill Park'},
    {id: 612, name: 'BKB'},
    {id: 613, name: 'BP Mosman (9542)'},
    {id: 614, name: 'Caltex Five Dock'},
    {id: 615, name: 'Total Fuel Cabramatta'},
    {id: 616, name: 'Speedway North St Marys'},
    {id: 617, name: 'Caltex Woolworths Berkshire Park'},
    {id: 618, name: 'Caltex St Marys'},
    {id: 619, name: 'Coles Express Berkshire Park'},
    {id: 620, name: 'BP Maraylya'},
    {id: 621, name: 'Caltex Woolworths Plumpton'},
    {id: 622, name: 'Westside Doonside'},
    {id: 623, name: '7-Eleven Hassall Grove'},
    {id: 624, name: 'BP St Marys'},
    {id: 625, name: 'BP St Marys (Forrester Road)'},
    {id: 626, name: '7-Eleven Plumpton'},
    {id: 627, name: '7-Eleven RIVERSTONE'},
    {id: 628, name: 'Caltex Woolworths Vineyard'},
    {id: 629, name: 'BP Shalvey'},
    {id: 630, name: 'Coles Express Colyton'},
    {id: 631, name: 'Coles Express Eastern Creek'},
    {id: 632, name: 'Coles Express Doonside'},
    {id: 633, name: '7-Eleven St Marys'},
    {id: 634, name: '7-Eleven Colyton'},
    {id: 635, name: '7-Eleven Minchinbury'},
    {id: 636, name: '7-Eleven Eastern Creek'},
    {id: 637, name: '7-Eleven Rooty Hill'},
    {id: 638, name: 'Coles Express Marsden Park'},
    {id: 639, name: 'Coles Express Parklea'},
    {id: 640, name: '7-Eleven Quakers Hill'},
    {id: 641, name: '7-Eleven Marsden Park'},
    {id: 642, name: 'BP Quakers Hill'},
    {id: 643, name: 'Caltex Woolworths Mount Druitt'},
    {id: 644, name: 'FREEDOM FUEL VINEYARD'},
    {id: 645, name: 'Independent Riverstone'},
    {id: 646, name: 'Costco Marsden Park (Members only)'},
    {id: 647, name: 'Caltex Parklea'},
    {id: 648, name: 'Caltex Eastern Creek'},
    {id: 649, name: 'Caltex Marsden Park'},
    {id: 650, name: '7-Eleven Mount Druitt'},
    {id: 651, name: 'Puma Energy Marsden Park'},
    {id: 652, name: '7-Eleven Emerton'},
    {id: 653, name: 'Caltex Mount Druitt'},
    {id: 654, name: 'BP Eastern Creek T/S'},
    {id: 655, name: 'BP Glendenning'},
    {id: 656, name: 'BP Woodcroft'},
    {id: 657, name: 'BP Riverstone'},
    {id: 658, name: 'Metro Fuel Doonside'},
    {id: 659, name: 'BP Marsden Park'},
    {id: 660, name: 'Metro Petroleum St Marys'},
    {id: 661, name: 'United Petroleum Lethbridge Park'},
    {id: 662, name: 'BP Minchinbury'},
]